### ISSUE TITLE
Calculation of Balance Measure II

### ISSUE THREAD

**Issue by anel-li** [anel-li/ValueBalance#3]
Calculationt he length of line between value item

**Comment by anel-li** [comment]
length balance measure is created and checked =)

**Comment by hwayment** [comment]
HI, I’m in GitHub now, trying to learn something—seems pretty daunting at this point!

On Feb 26, 2021, at 2:46 PM, el.le <notifications@github.com<mailto:notifications@github.com>> wrote:



length balance measure is created and checked =)

**Comment by anel-li** [comment]
two length measures were created:

BL1: on the level of 10 basic values (POW, ACH, BEN, UNI)
BL2: on the level of 21 items - taking only the SEN and STR items into account (9 variables)

In order to transfer the idea of these measures, we created an explanatory graph
