### ISSUE TITLE
Factor analysis

### ISSUE THREAD

**Issue by AnnamariaTatrai** [anel-li/ValueBalance#5]
Based on Verkasalo's publication another balance-measure

**Comment by hwayment** [comment]
Are you using the published factor loadings? I also put them in our draft.

**Comment by anel-li** [comment]
after running the factor analysis we decided to use the published factor loadings, based an Verkasalos paper, this will give us the opportunity to test these and compare the results with verkasalos et al.

Paper:
Verkasalo, Markku, Jan-Erik Lönnqvist, Jari Lipsanen and Klaus Helkama, 2009: European Norms and Equations for a Two Dimensional Presentation of Values as Measured with Schwartz’s 21‐Item Portrait Values Questionnaire. European Journal of Social Psychologyb39(5): 780–792. https://doi.org/10.1002/ejsp.580
