### ISSUE TITLE
Preparation of tables for thesis 

### ISSUE THREAD

**Issue by anel-li** [anel-li/ValueBalance#9]
to be created: - taking 9 rounds into account
- table showing final number of cases per wave (final Ns)
- table of exploratory variables
- table of outcome variables

- table of PVQs -> postponed

-> removing blanks!

**Comment by anel-li** [comment]
- table of balance measures

**Comment by hwayment** [comment]
I took the raw data you posted in dropbox excel files and created tables in our current draft
